version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-jogo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jogo_portos
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: jogo-dos-portos
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/jogo_portos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  db_data:
